services:
  postgres:
    container_name: postgres_container
    image: postgres:latest # Specify the version or use 'latest'
    environment:
      POSTGRES_USER: yug
      POSTGRES_PASSWORD: yug
      PGDATA: /var/lib/postgresql/data # Default PG data directory
    volumes:
      - postgres:/var/lib/postgresql/data # Match PGDATA with the default directory
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest # Specify version or use 'latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: yug@gmail.com
      PGADMIN_DEFAULT_PASSWORD: yug
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
